#!/usr/bin/python3
import sys
import psycopg2
if len(sys.argv) < 3:
    print("Usage: ./courses-studied studentID term")
    exit(1)
studentID = sys.argv[1]
term=sys.argv[2]
conn=None
errqry=f"""select * from students where id = {studentID}"""
qry="""select s.code, s.name from subjects s 
    join courses c on c.subject=s.id
    join course_enrolments ce on ce.course=c.id
    join terms t on t.id = c.term
    where t.code = %s and ce.student=%s order by s.code"""
try:
    conn = psycopg2.connect(f"dbname=uni")
    cur = conn.cursor()
    cur.execute(errqry,[studentID])
    student=cur.fetchone()
    if not student:
        print("No such student")
        exit(1)
    cur.execute(qry,[term,studentID])
    courses=cur.fetchall()
    for course in courses:
        print(course[0], course[1])
    
except psycopg2.Error as err:
    print("database error: ", err)
finally:
    if conn is not None:
        conn.close()
